### ISSUE TITLE
Error occurred while browsing /query on micro web

### ISSUE THREAD

**Issue by sakti** [micro/micro#36]
runtime error: index out of range on github.com/micro/micro/web/web.go:255
```
2016/04/13 13:53:27 Listening on [::]:8082
2016/04/13 13:53:27 Listening on [::]:33346
2016/04/13 13:53:27 Broker Listening on [::]:33286
2016/04/13 13:53:27 Registering node: go.micro.web-6cfd3255-0144-11e6-be9d-10bf48675864
2016/04/13 13:53:31 http: panic serving 127.0.0.1:57578: runtime error: index out of range
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc8200aee00)
	/home/sdc/go/src/net/http/server.go:1389 +0xc1
panic(0x9d96a0, 0xc82000e100)
	/home/sdc/go/src/runtime/panic.go:426 +0x4e9
github.com/micro/micro/web.queryHandler(0x7fdb65f52298, 0xc8200122a0, 0xc820114000)
	/home/sdc/go-project/src/github.com/micro/micro/web/web.go:255 +0x72b
net/http.HandlerFunc.ServeHTTP(0xbbcd40, 0x7fdb65f52298, 0xc8200122a0, 0xc820114000)
	/home/sdc/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820097310, 0x7fdb65f52298, 0xc8200122a0, 0xc820114000)
	/home/sdc/go-project/src/github.com/gorilla/mux/mux.go:103 +0x270
github.com/micro/micro/web.(*srv).ServeHTTP(0xc820092068, 0x7fdb65f52298, 0xc8200122a0, 0xc820114000)
	/home/sdc/go-project/src/github.com/micro/micro/web/web.go:64 +0x246
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7fdb65f13330, 0xc820092010, 0x7fdb65f17f30, 0xc820092068, 0x7fdb65f520f8, 0xc8200f61a0, 0xc820114000)
	/home/sdc/go-project/src/github.com/gorilla/handlers/handlers.go:77 +0x121
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc8200e5920, 0x7fdb65f520f8, 0xc8200f61a0, 0xc820114000)
	<autogenerated>:15 +0xb4
net/http.(*ServeMux).ServeHTTP(0xc82016c810, 0x7fdb65f520f8, 0xc8200f61a0, 0xc820114000)
	/home/sdc/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820176000, 0x7fdb65f520f8, 0xc8200f61a0, 0xc820114000)
	/home/sdc/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8200aee00)
	/home/sdc/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/home/sdc/go/src/net/http/server.go:2137 +0x44e
```

**Comment by asim** [comment]
Fixed https://github.com/micro/micro/commit/deee9096d51bf93dbfa3bca0e5ed97917847b798. Thanks.

**Comment by sakti** [comment]
Yup, fixed. Thanks :)
