### ISSUE TITLE
[BUG] micro http proxy panic on start

### ISSUE THREAD

**Issue by atakanozceviz** [micro/micro#567]
```bash
$ micro proxy --protocol http
```

```
2020-02-25 11:59:06 Proxy [http] serving protocol: http
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1293758]

goroutine 1 [running]:
github.com/micro/micro/v2/proxy.run(0xc00034d3c0, 0xc00000f2d8, 0x2, 0x2)
	/home/runner/work/micro/micro/proxy/proxy.go:257 +0xdd8
github.com/micro/micro/v2/proxy.Commands.func1(0xc00034d3c0, 0x6, 0xa)
	/home/runner/work/micro/micro/proxy/proxy.go:304 +0x46
github.com/micro/cli/v2.(*Command).Run(0xc000342fc0, 0xc00034d180, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/command.go:161 +0x4b9
github.com/micro/cli/v2.(*App).RunContext(0xc000001500, 0x196b0c0, 0xc0000d0010, 0xc0000d8040, 0x4, 0x4, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/app.go:303 +0x790
github.com/micro/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/app.go:210
github.com/micro/cli/v2.(*App).RunAndExitOnError(0xc000001500)
	/home/runner/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/app.go:324 +0x6b
github.com/micro/go-micro/v2/config/cmd.(*cmd).Init(0xc00023e000, 0xc000237840, 0x3, 0x3, 0x23c5380, 0xc000070750)
	/home/runner/go/pkg/mod/github.com/micro/go-micro/v2@v2.1.2/config/cmd/cmd.go:661 +0xe9
github.com/micro/go-micro/v2/config/cmd.Init(...)
	/home/runner/go/pkg/mod/github.com/micro/go-micro/v2@v2.1.2/config/cmd/cmd.go:674
github.com/micro/micro/v2/cmd.Init(0x0, 0x0, 0x0)
	/home/runner/work/micro/micro/cmd/cmd.go:257 +0x12c
main.main()
	/home/runner/work/micro/micro/main.go:8 +0x32
```

micro version: `2.1.1`

**Comment by printfcoder** [comment]
proxy server needs a httpServer which has not been implemented. so http protocol is a todo feature.
