### ISSUE TITLE
micro sidecar / PubSub: Concurrent write to websocket

### ISSUE THREAD

**Issue by fenderle** [micro/micro#74]
Sometimes I get a panic for which I don't know yet how to reproduce. However, here is the stack trace, which maybe gives a hint to a potential problem.

```
[18:16:12] micro[72397] 2016/11/18 18:16:12 http: panic serving 10.49.80.160:55355: concurrent write to websocket connection
[18:16:12] micro[72397] goroutine 55 [running]:
[18:16:12] micro[72397] net/http.(*conn).serve.func1(0xc42016e280)
[18:16:12] micro[72397] 	/usr/local/go/src/net/http/server.go:1491 +0x12a
[18:16:12] micro[72397] panic(0x53b4c0, 0xc420266320)
[18:16:12] micro[72397] 	/usr/local/go/src/runtime/panic.go:458 +0x243
[18:16:12] micro[72397] github.com/gorilla/websocket.(*Conn).flushFrame(0xc4200ae280, 0xc420664001, 0xc42066404b, 0x0, 0x19, 0x0, 0x5d5e5)
[18:16:12] micro[72397] 	/Users/ana-enderfra/Develop/go/src/github.com/gorilla/websocket/conn.go:519 +0x45e
[18:16:12] micro[72397] github.com/gorilla/websocket.(*Conn).WriteMessage(0xc4200ae280, 0x1, 0xc420664024, 0x27, 0x40, 0x0, 0x0)
[18:16:12] micro[72397] 	/Users/ana-enderfra/Develop/go/src/github.com/gorilla/websocket/conn.go:657 +0x13b
[18:16:12] micro[72397] github.com/micro/micro/internal/handler.(*conn).write(0xc420320480, 0x1, 0xc420664024, 0x27, 0x40, 0x0, 0x0)
[18:16:12] micro[72397] 	/Users/ana-enderfra/Develop/go/src/github.com/micro/micro/internal/handler/broker.go:62 +0xe7
[18:16:12] micro[72397] github.com/micro/micro/internal/handler.(*conn).writeLoop.func1(0x893ba0, 0xc420336440, 0xc42006fae0, 0x50)
[18:16:12] micro[72397] 	/Users/ana-enderfra/Develop/go/src/github.com/micro/micro/internal/handler/broker.go:79 +0x97
[18:16:12] micro[72397] github.com/micro/go-micro/broker.(*httpBroker).ServeHTTP(0xc4200bc370, 0x8944a0, 0xc4200f8000, 0xc4201722d0)
[18:16:12] micro[72397] 	/Users/ana-enderfra/Develop/go/src/github.com/micro/go-micro/broker/http_broker.go:295 +0x43b
[18:16:12] micro[72397] net/http.(*ServeMux).ServeHTTP(0xc420077230, 0x8944a0, 0xc4200f8000, 0xc4201722d0)
[18:16:12] micro[72397] 	/usr/local/go/src/net/http/server.go:2022 +0x7f
[18:16:12] micro[72397] net/http.serverHandler.ServeHTTP(0xc4204fc080, 0x8944a0, 0xc4200f8000, 0xc4201722d0)
[18:16:12] micro[72397] 	/usr/local/go/src/net/http/server.go:2202 +0x7d
[18:16:12] micro[72397] net/http.(*conn).serve(0xc42016e280, 0x894e20, 0xc420072b00)
[18:16:12] micro[72397] 	/usr/local/go/src/net/http/server.go:1579 +0x4b7
[18:16:12] micro[72397] created by net/http.(*Server).Serve
[18:16:12] micro[72397] 	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by asim** [comment]
Can you update your version of micro please. It's out dated and some of the line numbers don't match.

**Comment by asim** [comment]
If you google the issue it seems gorilla websocket package is not thread safe. Using mutex. Commit here. https://github.com/micro/micro/commit/21e1c50f4bcccf41c0c18b01baea4ad8f7487a14
